### ISSUE TITLE
Changing locale

### ISSUE THREAD

**Issue by Hucho** [fetchlogic/amz-products#2]
Hallo,

first: this is a great module...it is easy to handle and works just fine...

Question: I would like to query products from the german amazon service..

How can I set the locale? I have tried many options and can't address the german server.
(Of course: I use a german associate ID)

Is the locale preset in this module?

Thanks

Hucho

**Comment by jwd2a** [comment]
Thanks! I've patched the module to accept a `locale` setting when initializing. It defaults to `US`, but you should be able to pass in `DE` to access German resources. Full disclosure, I haven't tested this against that data source because I don't have a German associate ID, but the calls to the US source work fine. Let me know how it works for you!
